const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';

export {
    ADD_PRODUCT_SUCCESS,
    FETCH_PRODUCT_SUCCESS,
    FETCH_PRODUCTS_SUCCESS,
    FILTER_PRODUCTS,
    REMOVE_PRODUCT_SUCCESS,
    UPDATE_PRODUCT_SUCCESS
};